# 1. Imports

In [1]:
from music_library_tools.library import load_library, get_library_section, parse_dict_elements
import pandas as pd

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

# 2. Load Library XML

In [3]:
xml_path = "/Users/stephenusher/Documents/Steve's Folder/music-library-tools/exports/raw/"
xml_file = xml_path + "MusicLibrary_2026_08_03.xml"
library = load_library(xml_file)

# 3. Parse Track Dictionaries

In [4]:
tracks = get_library_section(library, 'Tracks')
parsed_tracks = parse_dict_elements(tracks)

In [5]:
len(parsed_tracks)

19030

In [6]:
parsed_tracks[0]

{'Track ID': 1704,
 'Name': 'Hells Bells',
 'Artist': 'AC/DC',
 'Album': 'Back In Black',
 'Genre': 'Rock',
 'Kind': 'Purchased AAC audio file',
 'Size': 11038209,
 'Total Time': 312400,
 'Disc Number': 1,
 'Disc Count': 1,
 'Track Number': 1,
 'Track Count': 10,
 'Year': 1980,
 'BPM': 192,
 'Date Modified': '2026-04-13T15:36:42Z',
 'Date Added': '2008-08-24T16:32:34Z',
 'Bit Rate': 256,
 'Sample Rate': 44100,
 'Comments': 'Owner: Steve',
 'Play Count': 8,
 'Play Date': 3704810164,
 'Play Date UTC': '2021-05-25T16:56:04Z',
 'Skip Count': 1,
 'Skip Date': '2014-07-15T14:13:42Z',
 'Rating': 60,
 'Album Rating': 60,
 'Album Rating Computed': True,
 'Normalization': 7211,
 'Sort Album': 'AC/DC - 1980',
 'Persistent ID': 'EA6442D8ED513382',
 'Track Type': 'File',
 'Location': 'file:///Volumes/Steve/Music/iTunes/Music/AC_DC/Back%20In%20Black/01%20Hells%20Bells.m4a',
 'File Folder Count': 5,
 'Library Folder Count': 1}

# 4. Create DataFrame

In [7]:
df = pd.DataFrame(parsed_tracks)

In [8]:
df.shape

(19030, 61)

In [9]:
df.columns

Index(['Track ID', 'Name', 'Artist', 'Album', 'Genre', 'Kind', 'Size',
       'Total Time', 'Disc Number', 'Disc Count', 'Track Number',
       'Track Count', 'Year', 'BPM', 'Date Modified', 'Date Added', 'Bit Rate',
       'Sample Rate', 'Comments', 'Play Count', 'Play Date', 'Play Date UTC',
       'Skip Count', 'Skip Date', 'Rating', 'Album Rating',
       'Album Rating Computed', 'Normalization', 'Sort Album', 'Persistent ID',
       'Track Type', 'Location', 'File Folder Count', 'Library Folder Count',
       'Favorited', 'Loved', 'Part Of Gapless Album', 'Sort Artist',
       'Composer', 'Sort Name', 'Artwork Count', 'Disabled', 'Sort Composer',
       'Grouping', 'Purchased', 'Album Artist', 'Sort Album Artist', 'Matched',
       'File Type', 'Compilation', 'Release Date', 'Explicit', 'Protected',
       'Apple Music', 'Work', 'Movement Number', 'Movement Count',
       'Movement Name', 'Clean', 'Playlist Only', 'Rating Computed'],
      dtype='str')

In [10]:
df[(df['Name'] == 'Hysteria') & (df['Album'] == 'H.A.A.R.P [Live]')][[
    'Track ID', 'Kind', 'Date Added', 'Date Modified',
    'Play Count', 'Play Date UTC', 'Rating', 'Persistent ID',
    'Location', 'Apple Music']]

,Track ID,Kind,Date Added,Date Modified,Play Count,Play Date UTC,Rating,Persistent ID,Location,Apple Music
1705,5127,Matched AAC audio file,2008-08-29T13:17:33Z,2013-02-28T11:30:34Z,30.0,2023-07-05T11:54:01Z,100.0,3A824B783238663C,file:///Volumes/Steve/Music/iTunes/Music/Muse/H.A.A.R.P%20%5BLive%5D/03%20Hysteria.m4a,NaN
11123,25406,AAC audio file,2026-04-13T18:18:50Z,2013-02-28T11:30:34Z,NaN,NaN,NaN,0CA86F682DAB0062,NaN,NaN

In [11]:
row_count = len(df)
profile = []
for column in df.columns:
    present = df[column].count()
    missing = row_count - present
    first_value = df[column].dropna().iloc[0]
    col_type = type(first_value).__name__
    profile.append({
        'Column': column,
        'Type': col_type,
        'Present': present,
        'Missing': missing,
        'Percentage Present': round(100 * present / row_count, 2)
    })
field_profile = pd.DataFrame(profile).sort_values(by='Present', ascending=False)
print(field_profile.to_markdown(index=False))

| Column                | Type    |   Present |   Missing |   Percentage Present |
|:----------------------|:--------|----------:|----------:|---------------------:|
| Track ID              | int64   |     19030 |         0 |               100    |
| Total Time            | int64   |     19030 |         0 |               100    |
| Name                  | str     |     19030 |         0 |               100    |
| Persistent ID         | str     |     19030 |         0 |               100    |
| Sample Rate           | int64   |     19030 |         0 |               100    |
| Bit Rate              | int64   |     19030 |         0 |               100    |
| Track Type            | str     |     19030 |         0 |               100    |
| Size                  | int64   |     19030 |         0 |               100    |
| Kind                  | str     |     19030 |         0 |               100    |
| Album                 | str     |     19019 |        11 |                99.94 |
| Artist                | str     |     19019 |        11 |                99.94 |
| Genre                 | str     |     19019 |        11 |                99.94 |
| Track Number          | float64 |     19016 |        14 |                99.93 |
| Date Modified         | str     |     19004 |        26 |                99.86 |
| Sort Album            | str     |     18983 |        47 |                99.75 |
| Track Count           | float64 |     18976 |        54 |                99.72 |
| Year                  | float64 |     18965 |        65 |                99.66 |
| Date Added            | str     |     18929 |       101 |                99.47 |
| Comments              | str     |     18825 |       205 |                98.92 |
| Disc Number           | float64 |     18528 |       502 |                97.36 |
| Normalization         | float64 |     18500 |       530 |                97.21 |
| Disc Count            | float64 |     18492 |       538 |                97.17 |
| Composer              | str     |     13433 |      5597 |                70.59 |
| Album Rating          | float64 |     12572 |      6458 |                66.06 |
| Album Rating Computed | bool    |     12287 |      6743 |                64.57 |
| Library Folder Count  | float64 |      9939 |      9091 |                52.23 |
| File Folder Count     | float64 |      9939 |      9091 |                52.23 |
| Location              | str     |      9939 |      9091 |                52.23 |
| Artwork Count         | float64 |      7778 |     11252 |                40.87 |
| Sort Artist           | str     |      7629 |     11401 |                40.09 |
| Play Date UTC         | str     |      7553 |     11477 |                39.69 |
| Play Date             | float64 |      7553 |     11477 |                39.69 |
| Play Count            | float64 |      7461 |     11569 |                39.21 |
| Album Artist          | str     |      7429 |     11601 |                39.04 |
| Rating                | float64 |      6874 |     12156 |                36.12 |
| Release Date          | str     |      6642 |     12388 |                34.9  |
| Matched               | bool    |      5127 |     13903 |                26.94 |
| Compilation           | bool    |      4068 |     14962 |                21.38 |
| Sort Name             | str     |      2522 |     16508 |                13.25 |
| Sort Album Artist     | str     |      1569 |     17461 |                 8.24 |
| Apple Music           | bool    |      1434 |     17596 |                 7.54 |
| Favorited             | bool    |      1412 |     17618 |                 7.42 |
| Loved                 | bool    |      1412 |     17618 |                 7.42 |
| BPM                   | float64 |      1108 |     17922 |                 5.82 |
| Protected             | bool    |       902 |     18128 |                 4.74 |
| Part Of Gapless Album | bool    |       813 |     18217 |                 4.27 |
| Sort Composer         | str     |       519 |     18511 |                 2.73 |
| Purchased             | bool    |       370 |     18660 |                 1.94 |
| Skip Date             | str     |       307 |     18723 |                 1.61 |
| Skip Count            | float64 |       279 |     18751 |                 1.47 |
| Grouping              | str     |       230 |     18800 |                 1.21 |
| Work                  | str     |       156 |     18874 |                 0.82 |
| Movement Name         | str     |       155 |     18875 |                 0.81 |
| Rating Computed       | bool    |       131 |     18899 |                 0.69 |
| Playlist Only         | bool    |       101 |     18929 |                 0.53 |
| Explicit              | bool    |        86 |     18944 |                 0.45 |
| Movement Number       | float64 |        52 |     18978 |                 0.27 |
| Movement Count        | float64 |        52 |     18978 |                 0.27 |
| File Type             | float64 |        11 |     19019 |                 0.06 |
| Clean                 | bool    |        10 |     19020 |                 0.05 |
| Disabled              | bool    |         1 |     19029 |                 0.01 |

In [12]:
classification_columns = ['Track Type',
                          'Kind',
                          'Comments',
                          'Matched',
                          'Purchased',
                          'Apple Music',
                          'Compilation',
                          'Protected']
for column in classification_columns:
    print(df[column].value_counts(dropna=False))

Track Type
File      9939
Remote    9091
Name: count, dtype: int64
Kind
AAC audio file                10240
Matched AAC audio file         6810
Apple Music AAC audio file     1430
Purchased AAC audio file        348
MPEG audio file                 200
WAV audio file                    2
Name: count, dtype: int64
Comments
Owner: Steve                                    11287
Owner: Rachel                                    5463
Owner: Steve and Rachel                           656
Owner: Steve (Apple Music Album)                  612
Owner:  Steve                                     253
Owner: Steve & Rachel                             213
NaN                                               205
Owner:  Chloë                                     126
Owner: Rachel and Steve                            97
Owner:  Rachel                                     82
Piano                                              17
Owner: Chloë                                        7
Owner: Chloë, Rachel                                3
Owner: Rachel  (David Jost & Twin Radio Mix)        2
Owner:  Chloë, Rachel                               2
Owner: Steve, Rachel                                1
Owner: Rachel, Chloë                                1
Owner: None                                         1
Owner:  Chloe                                       1
Album Release Date: 15/09/2023                      1
Name: count, dtype: int64
Matched
NaN     13903
True     5127
Name: count, dtype: int64
Purchased
NaN     18660
True      370
Name: count, dtype: int64
Apple Music
NaN     17596
True     1434
Name: count, dtype: int64
Compilation
NaN     14962
True     4068
Name: count, dtype: int64
Protected
NaN     18128
True      902
Name: count, dtype: int64

In [13]:
track_type_v_kind = pd.crosstab(df['Track Type'], df['Kind'])
print(track_type_v_kind.to_markdown())

| Track Type   |   AAC audio file |   Apple Music AAC audio file |   MPEG audio file |   Matched AAC audio file |   Purchased AAC audio file |   WAV audio file |
|:-------------|-----------------:|-----------------------------:|------------------:|-------------------------:|---------------------------:|-----------------:|
| File         |             1872 |                          898 |                10 |                     6810 |                        348 |                1 |
| Remote       |             8368 |                          532 |               190 |                        0 |                          0 |                1 |

In [14]:
track_type_v_matched = pd.crosstab(df['Track Type'], df['Matched'])
print(track_type_v_matched.to_markdown())

| Track Type   |   True |
|:-------------|-------:|
| File         |     25 |
| Remote       |   5102 |

In [15]:
track_type_v_apple_music = pd.crosstab(df['Track Type'], df['Apple Music'])
print(track_type_v_apple_music.to_markdown())

| Track Type   |   True |
|:-------------|-------:|
| File         |    902 |
| Remote       |    532 |

In [16]:
track_type_v_location = pd.crosstab(df['Track Type'], df['Location'].notna())
print(track_type_v_location.to_markdown())

| Track Type   |   False |   True |
|:-------------|--------:|-------:|
| File         |       0 |   9939 |
| Remote       |    9091 |      0 |

In [17]:
kind_v_matched = pd.crosstab(df['Kind'], df['Matched'].notna())
print(kind_v_matched.to_markdown())

| Kind                       |   False |   True |
|:---------------------------|--------:|-------:|
| AAC audio file             |    5241 |   4999 |
| Apple Music AAC audio file |    1430 |      0 |
| MPEG audio file            |      97 |    103 |
| Matched AAC audio file     |    6785 |     25 |
| Purchased AAC audio file   |     348 |      0 |
| WAV audio file             |       2 |      0 |

In [18]:
df['Persistent ID'].is_unique

True

In [19]:
df['Track ID'].is_unique

True

In [20]:
cols = ['Name', 'Artist', 'Album', 'Persistent ID', 'Track ID']
for col in cols:
    print(f"Column: {col}")
    print(f"No. of unique values: {df[col].nunique()}")

Column: Name
No. of unique values: 9093
Column: Artist
No. of unique values: 1898
Column: Album
No. of unique values: 1013
Column: Persistent ID
No. of unique values: 19030
Column: Track ID
No. of unique values: 19030

In [21]:
df.groupby(['Name', 'Artist']).size().max()

np.int64(17)

In [22]:
df.groupby(['Name', 'Artist', 'Album']).size().max()

np.int64(4)

In [23]:
name_artist_album = (
    df.groupby(["Name", "Artist", "Album"])
      .size()
      .reset_index(name="Count")
)

len(name_artist_album[name_artist_album["Count"] > 1])

8107

In [24]:
name_artist_album_time = (
    df.groupby(["Name", "Artist", "Album", "Total Time"])
      .size()
      .reset_index(name="Count")
)

len(name_artist_album_time[name_artist_album_time["Count"] > 1])

8028

# Case Study: Known Removed Tracks

In [25]:
def compare_replacements(name, album, artist):
    fields = ['Artist', 'Album', 'Name', 'Track ID', 'Persistent ID', 'Kind', 'Track Type', 'Location', 'Play Count', 'Rating']
    comparison = df[(df['Name'] == name) & (df['Album'] == album) & (df['Artist'] == artist)][fields].T
    comparison.columns = ['Original', 'Replacement']
    return comparison.to_markdown()

In [26]:
name = 'Hysteria'
album = 'H.A.A.R.P [Live]'
artist = 'Muse'
print(compare_replacements(name, album, artist))

|               | Original                                                                               | Replacement      |
|:--------------|:---------------------------------------------------------------------------------------|:-----------------|
| Artist        | Muse                                                                                   | Muse             |
| Album         | H.A.A.R.P [Live]                                                                       | H.A.A.R.P [Live] |
| Name          | Hysteria                                                                               | Hysteria         |
| Track ID      | 5127                                                                                   | 25406            |
| Persistent ID | 3A824B783238663C                                                                       | 0CA86F682DAB0062 |
| Kind          | Matched AAC audio file                                                                 | AAC audio file   |
| Track Type    | File                                                                                   | Remote           |
| Location      | file:///Volumes/Steve/Music/iTunes/Music/Muse/H.A.A.R.P%20%5BLive%5D/03%20Hysteria.m4a | nan              |
| Play Count    | 30.0                                                                                   | nan              |
| Rating        | 100.0                                                                                  | nan              |

In [27]:
name = 'Blaze Of Glory'
album = 'Declaration'
artist = 'The Alarm'
print(compare_replacements(name, album, artist))

|               | Original                                                                                     | Replacement      |
|:--------------|:---------------------------------------------------------------------------------------------|:-----------------|
| Artist        | The Alarm                                                                                    | The Alarm        |
| Album         | Declaration                                                                                  | Declaration      |
| Name          | Blaze Of Glory                                                                               | Blaze Of Glory   |
| Track ID      | 1822                                                                                         | 25040            |
| Persistent ID | EA6442D8ED513F55                                                                             | A805F5B88945371A |
| Kind          | Matched AAC audio file                                                                       | AAC audio file   |
| Track Type    | File                                                                                         | Remote           |
| Location      | file:///Volumes/Steve/Music/iTunes/Music/The%20Alarm/Declaration/08%20Blaze%20Of%20Glory.m4a | nan              |
| Play Count    | 54.0                                                                                         | nan              |
| Rating        | 100.0                                                                                        | nan              |

In [28]:
name = 'Marching On'
album = 'Declaration'
artist = 'The Alarm'
print(compare_replacements(name, album, artist))

|               | Original                                                                                | Replacement      |
|:--------------|:----------------------------------------------------------------------------------------|:-----------------|
| Artist        | The Alarm                                                                               | The Alarm        |
| Album         | Declaration                                                                             | Declaration      |
| Name          | Marching On                                                                             | Marching On      |
| Track ID      | 1810                                                                                    | 25048            |
| Persistent ID | EA6442D8ED513F43                                                                        | 97413FB9BBCE5EB1 |
| Kind          | AAC audio file                                                                          | AAC audio file   |
| Track Type    | File                                                                                    | Remote           |
| Location      | file:///Volumes/Steve/Music/iTunes/Music/The%20Alarm/Declaration/02%20Marching%20On.m4a | nan              |
| Play Count    | 16.0                                                                                    | nan              |
| Rating        | 80.0                                                                                    | nan              |

In [29]:
def compare_differences(name, album, artist):
    comparison = df[(df['Name'] == name) & (df['Album'] == album) & (df['Artist'] == artist)].T
    assert len(comparison.columns) == 2, ('Expected exactly 2 matching tracks.')
    comparison.columns = ['Original', 'Replacement']
    mask = ~(
        comparison['Original'].isna() & comparison['Replacement'].isna()
    ) & (
        comparison['Original'] != comparison['Replacement']
    )
    comparison = comparison[mask]
    print(f"There were {len(comparison)} fields changed in the replacement track.")
    return comparison

In [30]:
name = 'Hysteria'
album = 'H.A.A.R.P [Live]'
artist = 'Muse'
print(compare_differences(name, album, artist).to_markdown())

There were 17 fields changed in the replacement track.
|                      | Original                                                                               | Replacement          |
|:---------------------|:---------------------------------------------------------------------------------------|:---------------------|
| Track ID             | 5127                                                                                   | 25406                |
| Kind                 | Matched AAC audio file                                                                 | AAC audio file       |
| Date Added           | 2008-08-29T13:17:33Z                                                                   | 2026-04-13T18:18:50Z |
| Play Count           | 30.0                                                                                   | nan                  |
| Play Date            | 3771406441.0                                                                           | nan                  |
| Play Date UTC        | 2023-07-05T11:54:01Z                                                                   | nan                  |
| Rating               | 100.0                                                                                  | nan                  |
| Persistent ID        | 3A824B783238663C                                                                       | 0CA86F682DAB0062     |
| Track Type           | File                                                                                   | Remote               |
| Location             | file:///Volumes/Steve/Music/iTunes/Music/Muse/H.A.A.R.P%20%5BLive%5D/03%20Hysteria.m4a | nan                  |
| File Folder Count    | 5.0                                                                                    | nan                  |
| Library Folder Count | 1.0                                                                                    | nan                  |
| Favorited            | True                                                                                   | nan                  |
| Loved                | True                                                                                   | nan                  |
| Artwork Count        | nan                                                                                    | 1.0                  |
| Matched              | nan                                                                                    | True                 |
| Release Date         | nan                                                                                    | 2008-03-17T07:00:00Z |

In [31]:
name = 'Blaze Of Glory'
album = 'Declaration'
artist = 'The Alarm'
print(compare_differences(name, album, artist).to_markdown())

There were 17 fields changed in the replacement track.
|                      | Original                                                                                     | Replacement          |
|:---------------------|:---------------------------------------------------------------------------------------------|:---------------------|
| Track ID             | 1822                                                                                         | 25040                |
| Kind                 | Matched AAC audio file                                                                       | AAC audio file       |
| Date Added           | 2008-08-24T19:15:23Z                                                                         | 2026-04-13T18:18:50Z |
| Play Count           | 54.0                                                                                         | nan                  |
| Play Date            | 3750086987.0                                                                                 | nan                  |
| Play Date UTC        | 2022-10-31T18:49:47Z                                                                         | nan                  |
| Rating               | 100.0                                                                                        | nan                  |
| Persistent ID        | EA6442D8ED513F55                                                                             | A805F5B88945371A     |
| Track Type           | File                                                                                         | Remote               |
| Location             | file:///Volumes/Steve/Music/iTunes/Music/The%20Alarm/Declaration/08%20Blaze%20Of%20Glory.m4a | nan                  |
| File Folder Count    | 5.0                                                                                          | nan                  |
| Library Folder Count | 1.0                                                                                          | nan                  |
| Favorited            | True                                                                                         | nan                  |
| Loved                | True                                                                                         | nan                  |
| Sort Album Artist    | nan                                                                                          | Alarm                |
| Matched              | nan                                                                                          | True                 |
| Release Date         | nan                                                                                          | 1990-11-01T12:00:00Z |

In [32]:
name = 'Marching On'
album = 'Declaration'
artist = 'The Alarm'
print(compare_differences(name, album, artist).to_markdown())

There were 15 fields changed in the replacement track.
|                      | Original                                                                                | Replacement          |
|:---------------------|:----------------------------------------------------------------------------------------|:---------------------|
| Track ID             | 1810                                                                                    | 25048                |
| Date Added           | 2008-08-24T19:11:41Z                                                                    | 2026-04-13T18:18:50Z |
| Play Count           | 16.0                                                                                    | nan                  |
| Play Date            | 3765275067.0                                                                            | nan                  |
| Play Date UTC        | 2023-04-25T12:44:27Z                                                                    | nan                  |
| Rating               | 80.0                                                                                    | nan                  |
| Persistent ID        | EA6442D8ED513F43                                                                        | 97413FB9BBCE5EB1     |
| Track Type           | File                                                                                    | Remote               |
| Location             | file:///Volumes/Steve/Music/iTunes/Music/The%20Alarm/Declaration/02%20Marching%20On.m4a | nan                  |
| File Folder Count    | 5.0                                                                                     | nan                  |
| Library Folder Count | 1.0                                                                                     | nan                  |
| Favorited            | True                                                                                    | nan                  |
| Loved                | True                                                                                    | nan                  |
| Artwork Count        | nan                                                                                     | 1.0                  |
| Sort Album Artist    | nan                                                                                     | Alarm                |

In [33]:
name = 'Blaze of Glory'
album = 'The Sound & the Fury 1981-1991'
artist = 'The Alarm'
print(df[(df['Name'] == name) & (df['Album'] == album) & (df['Artist'] == artist)].T.to_markdown())

|                       | 10870                          |
|:----------------------|:-------------------------------|
| Track ID              | 24900                          |
| Name                  | Blaze of Glory                 |
| Artist                | The Alarm                      |
| Album                 | The Sound & the Fury 1981-1991 |
| Genre                 | Rock                           |
| Kind                  | AAC audio file                 |
| Size                  | 12219939                       |
| Total Time            | 360290                         |
| Disc Number           | 1.0                            |
| Disc Count            | 1.0                            |
| Track Number          | 29.0                           |
| Track Count           | 30.0                           |
| Year                  | 2005.0                         |
| BPM                   | nan                            |
| Date Modified         | 2024-04-29T06:51:37Z           |
| Date Added            | 2026-04-13T18:18:50Z           |
| Bit Rate              | 268                            |
| Sample Rate           | 44100                          |
| Comments              | Owner: Steve                   |
| Play Count            | nan                            |
| Play Date             | nan                            |
| Play Date UTC         | nan                            |
| Skip Count            | nan                            |
| Skip Date             | nan                            |
| Rating                | nan                            |
| Album Rating          | nan                            |
| Album Rating Computed | nan                            |
| Normalization         | 5662.0                         |
| Sort Album            | Alarm - 2008                   |
| Persistent ID         | 0A7D77FA812E26EE               |
| Track Type            | Remote                         |
| Location              | nan                            |
| File Folder Count     | nan                            |
| Library Folder Count  | nan                            |
| Favorited             | nan                            |
| Loved                 | nan                            |
| Part Of Gapless Album | nan                            |
| Sort Artist           | Alarm                          |
| Composer              | nan                            |
| Sort Name             | nan                            |
| Artwork Count         | 1.0                            |
| Disabled              | nan                            |
| Sort Composer         | nan                            |
| Grouping              | nan                            |
| Purchased             | nan                            |
| Album Artist          | The Alarm                      |
| Sort Album Artist     | Alarm                          |
| Matched               | True                           |
| File Type             | nan                            |
| Compilation           | nan                            |
| Release Date          | 2005-10-04T12:00:00Z           |
| Explicit              | nan                            |
| Protected             | nan                            |
| Apple Music           | nan                            |
| Work                  | nan                            |
| Movement Number       | nan                            |
| Movement Count        | nan                            |
| Movement Name         | nan                            |
| Clean                 | nan                            |
| Playlist Only         | nan                            |
| Rating Computed       | nan                            |

In [34]:
name = 'Thunder'
album = 'Evolve'
artist = 'Imagine Dragons'
print(df[(df['Name'] == name) & (df['Album'] == album) & (df['Artist'] == artist)].T.to_markdown())

|                       | 9313                                                                                       |
|:----------------------|:-------------------------------------------------------------------------------------------|
| Track ID              | 21231                                                                                      |
| Name                  | Thunder                                                                                    |
| Artist                | Imagine Dragons                                                                            |
| Album                 | Evolve                                                                                     |
| Genre                 | Alternative                                                                                |
| Kind                  | Apple Music AAC audio file                                                                 |
| Size                  | 6991910                                                                                    |
| Total Time            | 187144                                                                                     |
| Disc Number           | 1.0                                                                                        |
| Disc Count            | 1.0                                                                                        |
| Track Number          | 10.0                                                                                       |
| Track Count           | 12.0                                                                                       |
| Year                  | 2017.0                                                                                     |
| BPM                   | nan                                                                                        |
| Date Modified         | 2024-05-05T07:30:31Z                                                                       |
| Date Added            | 2018-04-04T10:55:22Z                                                                       |
| Bit Rate              | 256                                                                                        |
| Sample Rate           | 44100                                                                                      |
| Comments              | Owner: Steve (Apple Music Album)                                                           |
| Play Count            | 2.0                                                                                        |
| Play Date             | 3664174211.0                                                                               |
| Play Date UTC         | 2020-02-10T10:10:11Z                                                                       |
| Skip Count            | nan                                                                                        |
| Skip Date             | nan                                                                                        |
| Rating                | 40.0                                                                                       |
| Album Rating          | 60.0                                                                                       |
| Album Rating Computed | True                                                                                       |
| Normalization         | 6164.0                                                                                     |
| Sort Album            | Imagine Dragons - 2017                                                                     |
| Persistent ID         | 3692C819C255BAB0                                                                           |
| Track Type            | File                                                                                       |
| Location              | file:///Volumes/Steve/Music/iTunes/Apple%20Music/Imagine%20Dragons/Evolve/10%20Thunder.m4p |
| File Folder Count     | 5.0                                                                                        |
| Library Folder Count  | 1.0                                                                                        |
| Favorited             | nan                                                                                        |
| Loved                 | nan                                                                                        |
| Part Of Gapless Album | nan                                                                                        |
| Sort Artist           | Imagine Dragons                                                                            |
| Composer              | Dan Reynolds, Wayne Sermon, Ben McKee, Daniel Platzman, Jayson Dezuzio & A. Grant          |
| Sort Name             | Thunder                                                                                    |
| Artwork Count         | nan                                                                                        |
| Disabled              | nan                                                                                        |
| Sort Composer         | nan                                                                                        |
| Grouping              | nan                                                                                        |
| Purchased             | nan                                                                                        |
| Album Artist          | Imagine Dragons                                                                            |
| Sort Album Artist     | nan                                                                                        |
| Matched               | nan                                                                                        |
| File Type             | nan                                                                                        |
| Compilation           | nan                                                                                        |
| Release Date          | 2017-06-23T07:00:00Z                                                                       |
| Explicit              | nan                                                                                        |
| Protected             | True                                                                                       |
| Apple Music           | True                                                                                       |
| Work                  | nan                                                                                        |
| Movement Number       | nan                                                                                        |
| Movement Count        | nan                                                                                        |
| Movement Name         | nan                                                                                        |
| Clean                 | nan                                                                                        |
| Playlist Only         | nan                                                                                        |
| Rating Computed       | nan                                                                                        |

In [35]:
xml_file = xml_path + "MusicLibrary_2026_08_08.xml"
library2 = load_library(xml_file)

In [36]:
tracks2 = get_library_section(library2, 'Tracks')
parsed_tracks2 = parse_dict_elements(tracks2)

In [37]:
df2 = pd.DataFrame(parsed_tracks2)

In [39]:
name = 'Strength'
album = 'Strength 1985-1986'
artist = 'The Alarm'
strength_pre_download = df[(df['Name'] == name) & (df['Album'] == album) & (df['Artist'] == artist)].T

In [41]:
list(strength_pre_download.columns)

[59, 10977]

In [49]:
strength_pre_download.columns = ['Predownload Removed', 'Predownload Matched']
strength_pre_download

,Predownload Removed,Predownload Matched
Track ID,1832,25114
Name,Strength,Strength
Artist,The Alarm,The Alarm
Album,Strength 1985-1986,Strength 1985-1986
Genre,Rock,Rock
Kind,Matched AAC audio file,AAC audio file
Size,11674991,11674991
Total Time,334266,334266
Disc Number,1.0,1.0
Disc Count,1.0,1.0
Track Number,1.0,1.0
Track Count,17.0,17.0
Year,1985.0,1985.0
BPM,NaN,NaN
Date Modified,2014-10-13T11:53:49Z,2014-10-13T11:53:49Z
Date Added,2008-08-24T19:22:26Z,2026-04-13T18:18:50Z
Bit Rate,256,256
Sample Rate,44100,44100
Comments,Owner: Steve,Owner: Steve
Play Count,NaN,NaN
Play Date,3763026217.0,NaN
Play Date UTC,2023-03-30T12:03:37Z,NaN
Skip Count,NaN,NaN
Skip Date,NaN,NaN
Rating,80.0,NaN
Album Rating,60.0,60.0
Album Rating Computed,True,True
Normalization,3676.0,3676.0
Sort Album,Alarm - 1985,Alarm - 1985
Persistent ID,EA6442D8ED513FAE,6C4A5C5844ADE9EE
Track Type,File,Remote
Location,file:///Volumes/Steve/Music/iTunes/Music/The%20Alarm/Strength%201985-1986/01%20Strength.m4a,NaN
File Folder Count,5.0,NaN
Library Folder Count,1.0,NaN
Favorited,True,NaN
Loved,True,NaN
Part Of Gapless Album,NaN,NaN
Sort Artist,Alarm,Alarm
Composer,"Mike Peters, Dave Sharp, Eddie Macdonald, Nigel Twist","Mike Peters, Dave Sharp, Eddie Macdonald, Nigel Twist"
Sort Name,NaN,NaN
Artwork Count,NaN,1.0
Disabled,NaN,NaN
Sort Composer,NaN,NaN
Grouping,NaN,NaN
Purchased,NaN,NaN
Album Artist,NaN,NaN
Sort Album Artist,NaN,Alarm
Matched,NaN,True
File Type,NaN,NaN
Compilation,NaN,NaN
Release Date,NaN,1985-11-03T12:00:00Z
Explicit,NaN,NaN
Protected,NaN,NaN
Apple Music,NaN,NaN
Work,NaN,NaN
Movement Number,NaN,NaN
Movement Count,NaN,NaN
Movement Name,NaN,NaN
Clean,NaN,NaN
Playlist Only,NaN,NaN
Rating Computed,NaN,NaN

In [50]:
name = 'Strength'
album = 'Strength 1985-1986'
artist = 'The Alarm'
strength_post_download = df2[(df2['Name'] == name) & (df2['Album'] == album) & (df2['Artist'] == artist)].T

In [51]:
strength_post_download.columns = ['Postdownload Removed', 'Postdownload Matched']
strength_post_download

,Postdownload Removed,Postdownload Matched
Track ID,1828,25112
Name,Strength,Strength
Artist,The Alarm,The Alarm
Album,Strength 1985-1986,Strength 1985-1986
Genre,Rock,Rock
Kind,Matched AAC audio file,Purchased AAC audio file
Size,11674991,11608858
Total Time,334266,338493
Disc Number,1.0,1.0
Disc Count,1.0,1.0
Track Number,1.0,1.0
Track Count,17.0,17.0
Year,1985.0,1985.0
BPM,NaN,NaN
Date Modified,2014-10-13T11:53:49Z,2026-08-08T09:26:12Z
Date Added,2008-08-24T19:22:26Z,2026-04-13T18:18:50Z
Bit Rate,256,256
Sample Rate,44100,44100
Comments,Owner: Steve,Owner: Steve
Play Count,NaN,NaN
Play Date,3763026217.0,NaN
Play Date UTC,2023-03-30T12:03:37Z,NaN
Skip Count,NaN,NaN
Skip Date,NaN,NaN
Rating,80.0,NaN
Album Rating,60.0,60.0
Album Rating Computed,True,True
Normalization,3676.0,5738.0
Sort Album,Alarm - 1985,Alarm - 1985
Persistent ID,EA6442D8ED513FAE,6C4A5C5844ADE9EE
Track Type,File,File
Location,file:///Volumes/Steve/Music/iTunes/Music/The%20Alarm/Strength%201985-1986/01%20Strength.m4a,file:///Volumes/Steve/Music/iTunes/Music/The%20Alarm/Strength%201985-1986/01%20Strength%202.m4a
File Folder Count,5.0,5.0
Library Folder Count,1.0,1.0
Favorited,True,NaN
Loved,True,NaN
Part Of Gapless Album,NaN,NaN
Sort Artist,Alarm,Alarm
Composer,"Mike Peters, Dave Sharp, Eddie Macdonald, Nigel Twist","Mike Peters, Dave Sharp, Eddie Macdonald, Nigel Twist"
Sort Name,NaN,NaN
Artwork Count,NaN,NaN
Disabled,NaN,NaN
Sort Composer,NaN,NaN
Grouping,NaN,NaN
Purchased,NaN,True
Album Artist,NaN,NaN
Sort Album Artist,NaN,Alarm
Matched,NaN,NaN
File Type,NaN,NaN
Compilation,NaN,NaN
Release Date,NaN,1985-11-03T12:00:00Z
Explicit,NaN,NaN
Protected,NaN,NaN
Apple Music,NaN,NaN
Work,NaN,NaN
Movement Number,NaN,NaN
Movement Count,NaN,NaN
Movement Name,NaN,NaN
Clean,NaN,NaN
Playlist Only,NaN,NaN
Rating Computed,NaN,NaN

In [53]:
strength = pd.concat(
    [strength_pre_download, strength_post_download],
    axis=1,
    keys=['Predownload', 'Postdownload']
)
print(strength.to_markdown())

|                       | ('Predownload', 'Predownload Removed')                                                      | ('Predownload', 'Predownload Matched')                | ('Postdownload', 'Postdownload Removed')                                                    | ('Postdownload', 'Postdownload Matched')                                                        |
|:----------------------|:--------------------------------------------------------------------------------------------|:------------------------------------------------------|:--------------------------------------------------------------------------------------------|:------------------------------------------------------------------------------------------------|
| Track ID              | 1832                                                                                        | 25114                                                 | 1828                                                                                        | 25112                                                                                           |
| Name                  | Strength                                                                                    | Strength                                              | Strength                                                                                    | Strength                                                                                        |
| Artist                | The Alarm                                                                                   | The Alarm                                             | The Alarm                                                                                   | The Alarm                                                                                       |
| Album                 | Strength 1985-1986                                                                          | Strength 1985-1986                                    | Strength 1985-1986                                                                          | Strength 1985-1986                                                                              |
| Genre                 | Rock                                                                                        | Rock                                                  | Rock                                                                                        | Rock                                                                                            |
| Kind                  | Matched AAC audio file                                                                      | AAC audio file                                        | Matched AAC audio file                                                                      | Purchased AAC audio file                                                                        |
| Size                  | 11674991                                                                                    | 11674991                                              | 11674991                                                                                    | 11608858                                                                                        |
| Total Time            | 334266                                                                                      | 334266                                                | 334266                                                                                      | 338493                                                                                          |
| Disc Number           | 1.0                                                                                         | 1.0                                                   | 1.0                                                                                         | 1.0                                                                                             |
| Disc Count            | 1.0                                                                                         | 1.0                                                   | 1.0                                                                                         | 1.0                                                                                             |
| Track Number          | 1.0                                                                                         | 1.0                                                   | 1.0                                                                                         | 1.0                                                                                             |
| Track Count           | 17.0                                                                                        | 17.0                                                  | 17.0                                                                                        | 17.0                                                                                            |
| Year                  | 1985.0                                                                                      | 1985.0                                                | 1985.0                                                                                      | 1985.0                                                                                          |
| BPM                   | nan                                                                                         | nan                                                   | nan                                                                                         | nan                                                                                             |
| Date Modified         | 2014-10-13T11:53:49Z                                                                        | 2014-10-13T11:53:49Z                                  | 2014-10-13T11:53:49Z                                                                        | 2026-08-08T09:26:12Z                                                                            |
| Date Added            | 2008-08-24T19:22:26Z                                                                        | 2026-04-13T18:18:50Z                                  | 2008-08-24T19:22:26Z                                                                        | 2026-04-13T18:18:50Z                                                                            |
| Bit Rate              | 256                                                                                         | 256                                                   | 256                                                                                         | 256                                                                                             |
| Sample Rate           | 44100                                                                                       | 44100                                                 | 44100                                                                                       | 44100                                                                                           |
| Comments              | Owner: Steve                                                                                | Owner: Steve                                          | Owner: Steve                                                                                | Owner: Steve                                                                                    |
| Play Count            | nan                                                                                         | nan                                                   | nan                                                                                         | nan                                                                                             |
| Play Date             | 3763026217.0                                                                                | nan                                                   | 3763026217.0                                                                                | nan                                                                                             |
| Play Date UTC         | 2023-03-30T12:03:37Z                                                                        | nan                                                   | 2023-03-30T12:03:37Z                                                                        | nan                                                                                             |
| Skip Count            | nan                                                                                         | nan                                                   | nan                                                                                         | nan                                                                                             |
| Skip Date             | nan                                                                                         | nan                                                   | nan                                                                                         | nan                                                                                             |
| Rating                | 80.0                                                                                        | nan                                                   | 80.0                                                                                        | nan                                                                                             |
| Album Rating          | 60.0                                                                                        | 60.0                                                  | 60.0                                                                                        | 60.0                                                                                            |
| Album Rating Computed | True                                                                                        | True                                                  | True                                                                                        | True                                                                                            |
| Normalization         | 3676.0                                                                                      | 3676.0                                                | 3676.0                                                                                      | 5738.0                                                                                          |
| Sort Album            | Alarm - 1985                                                                                | Alarm - 1985                                          | Alarm - 1985                                                                                | Alarm - 1985                                                                                    |
| Persistent ID         | EA6442D8ED513FAE                                                                            | 6C4A5C5844ADE9EE                                      | EA6442D8ED513FAE                                                                            | 6C4A5C5844ADE9EE                                                                                |
| Track Type            | File                                                                                        | Remote                                                | File                                                                                        | File                                                                                            |
| Location              | file:///Volumes/Steve/Music/iTunes/Music/The%20Alarm/Strength%201985-1986/01%20Strength.m4a | nan                                                   | file:///Volumes/Steve/Music/iTunes/Music/The%20Alarm/Strength%201985-1986/01%20Strength.m4a | file:///Volumes/Steve/Music/iTunes/Music/The%20Alarm/Strength%201985-1986/01%20Strength%202.m4a |
| File Folder Count     | 5.0                                                                                         | nan                                                   | 5.0                                                                                         | 5.0                                                                                             |
| Library Folder Count  | 1.0                                                                                         | nan                                                   | 1.0                                                                                         | 1.0                                                                                             |
| Favorited             | True                                                                                        | nan                                                   | True                                                                                        | nan                                                                                             |
| Loved                 | True                                                                                        | nan                                                   | True                                                                                        | nan                                                                                             |
| Part Of Gapless Album | nan                                                                                         | nan                                                   | nan                                                                                         | nan                                                                                             |
| Sort Artist           | Alarm                                                                                       | Alarm                                                 | Alarm                                                                                       | Alarm                                                                                           |
| Composer              | Mike Peters, Dave Sharp, Eddie Macdonald, Nigel Twist                                       | Mike Peters, Dave Sharp, Eddie Macdonald, Nigel Twist | Mike Peters, Dave Sharp, Eddie Macdonald, Nigel Twist                                       | Mike Peters, Dave Sharp, Eddie Macdonald, Nigel Twist                                           |
| Sort Name             | nan                                                                                         | nan                                                   | nan                                                                                         | nan                                                                                             |
| Artwork Count         | nan                                                                                         | 1.0                                                   | nan                                                                                         | nan                                                                                             |
| Disabled              | nan                                                                                         | nan                                                   | nan                                                                                         | nan                                                                                             |
| Sort Composer         | nan                                                                                         | nan                                                   | nan                                                                                         | nan                                                                                             |
| Grouping              | nan                                                                                         | nan                                                   | nan                                                                                         | nan                                                                                             |
| Purchased             | nan                                                                                         | nan                                                   | nan                                                                                         | True                                                                                            |
| Album Artist          | nan                                                                                         | nan                                                   | nan                                                                                         | nan                                                                                             |
| Sort Album Artist     | nan                                                                                         | Alarm                                                 | nan                                                                                         | Alarm                                                                                           |
| Matched               | nan                                                                                         | True                                                  | nan                                                                                         | nan                                                                                             |
| File Type             | nan                                                                                         | nan                                                   | nan                                                                                         | nan                                                                                             |
| Compilation           | nan                                                                                         | nan                                                   | nan                                                                                         | nan                                                                                             |
| Release Date          | nan                                                                                         | 1985-11-03T12:00:00Z                                  | nan                                                                                         | 1985-11-03T12:00:00Z                                                                            |
| Explicit              | nan                                                                                         | nan                                                   | nan                                                                                         | nan                                                                                             |